/**
 * Caption line layout + active-word resolution — plan M10 item 5 ("per-word
 * karaoke-style animated caption rendering") and item 5's "reusing the same
 * trim/split affordances" for editing.
 *
 * v1 scope note (honest, not a silent gap): this renders ONE line of words,
 * left-to-right, no wrapping. The corpus's own guidance is short segments
 * ("2 lines max, 3-5 seconds each" per `05-capcut-ui-interactions.md` §9)
 * generated by `captions/generate.ts` at sentence/clause boundaries, so a
 * single unwrapped line covers the common case; multi-line wrap is a real,
 * scoped-out follow-up (see this task's `not_done`).
 */

import type { CaptionElement, CaptionWord } from "@/timeline/types";
import { buildTextFontString } from "@/text/primitives";
import { FONT_SIZE_SCALE_REFERENCE } from "@/text/typography";
import type { CaptionPosition } from "@/captions/styles";

export interface VisibleCaptionWord {
	word: CaptionWord;
	/** Index into `element.words` — stable across split/trim (see
	 * `CaptionWord`'s doc comment in `timeline/types.ts`) and what
	 * `commands/captions/update-caption-word.ts` expects. */
	index: number;
}

/** Words whose span intersects the currently-visible trimmed window
 * `[trimStart, trimStart + duration)`. */
export function getVisibleCaptionWords({
	element,
}: {
	element: CaptionElement;
}): VisibleCaptionWord[] {
	const windowStart = element.trimStart;
	const windowEnd = element.trimStart + element.duration;
	const result: VisibleCaptionWord[] = [];
	element.words.forEach((word, index) => {
		if (word.endTime > windowStart && word.startTime < windowEnd) {
			result.push({ word, index });
		}
	});
	return result;
}

/**
 * Index into `element.words` of the word "active" at `sourceLocalTime`
 * (ticks, in the same source-relative space as `CaptionWord.startTime`/
 * `endTime` and `element.trimStart`), or `null` before the first word has
 * started. A word that has already finished stays "active" through the gap
 * until the next word starts — reads as a sticky karaoke highlight rather
 * than flickering off between words, and matches how CapCut's own
 * word-highlight animation reads in practice.
 */
export function getActiveCaptionWordIndex({
	element,
	sourceLocalTime,
}: {
	element: CaptionElement;
	sourceLocalTime: number;
}): number | null {
	let activeIndex: number | null = null;
	for (let i = 0; i < element.words.length; i++) {
		const word = element.words[i];
		if (sourceLocalTime < word.startTime) break;
		activeIndex = i;
		if (sourceLocalTime < word.endTime) break;
	}
	return activeIndex;
}

export const CAPTION_POSITION_Y_FRACTION: Record<CaptionPosition, number> = {
	top: -0.36,
	center: 0,
	bottom: 0.36,
};

export interface MeasuredCaptionWord {
	text: string;
	/** Left edge, relative to the measured line's own left edge. */
	x: number;
	width: number;
	active: boolean;
}

export interface MeasuredCaptionLine {
	words: MeasuredCaptionWord[];
	totalWidth: number;
	totalHeight: number;
	fontString: string;
	scaledFontSize: number;
}

export type CaptionMeasureContext = Pick<
	CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D,
	"measureText" | "font"
>;

/**
 * Lays out one line of visible words left-to-right, joined by a single
 * space (punctuation is already glued onto its preceding word by the
 * mandatory smoothing pass upstream — `native-bridge/src/caption-smoothing.ts`
 * — so no extra spacing logic is needed here). `activeIndex` is an index
 * into `words` (the VISIBLE list passed in), not `element.words`.
 */
export function measureCaptionLine({
	words,
	activeIndex,
	uppercase,
	fontFamily,
	fontSize,
	fontWeight,
	canvasHeight,
	ctx,
}: {
	words: CaptionWord[];
	activeIndex: number | null;
	uppercase: boolean;
	fontFamily: string;
	fontSize: number;
	fontWeight: "normal" | "bold";
	canvasHeight: number;
	ctx: CaptionMeasureContext;
}): MeasuredCaptionLine {
	const scaledFontSize = fontSize * (canvasHeight / FONT_SIZE_SCALE_REFERENCE);
	const fontString = buildTextFontString({
		fontFamily,
		fontWeight,
		fontStyle: "normal",
		scaledFontSize,
	});
	ctx.font = fontString;

	const spaceWidth = ctx.measureText(" ").width;
	const measured: MeasuredCaptionWord[] = [];
	let cursor = 0;
	words.forEach((word, i) => {
		const display = uppercase ? word.text.toUpperCase() : word.text;
		const width = ctx.measureText(display).width;
		measured.push({ text: display, x: cursor, width, active: i === activeIndex });
		cursor += width + spaceWidth;
	});

	const totalWidth = Math.max(0, cursor - spaceWidth);
	return {
		words: measured,
		totalWidth,
		totalHeight: scaledFontSize * 1.3,
		fontString,
		scaledFontSize,
	};
}
